[package]
name = "motion"
version = "0.1.0"
edition = "2021"

[[example]]
path = "examples/main.rs"
name = "main"

[dependencies]
anyhow = "1.0.95"
tracing = "0.1.41"
tempfile = "3.15.0"
libheif-rs = { version = "1.0.2", path = "../libheif-rs" }
libultrahdr-rs = { path = "../libultrahdr-rs" }
mozjpeg = "0.10.12"
byteorder = "1.5.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["fmt"] }
clap = { version = "4.5.26", features = ["derive"] }

[build-dependencies]
vcpkg = "0.2.15"
